FROM nvcr.io/nvidia/l4t-ml:r32.5.0-py3 

RUN cd "$(dirname $(which python3))" \
    && rm -f /usr/bin/python && ln -s /usr/bin/python3 /usr/bin/python \
    && ln -s pip3 pip

ENV LANG C.UTF-8

RUN pip install scikit-build
WORKDIR /srv
COPY . .
RUN pip install -e ./vnet && pip install -e .
