version: '2.4'

services:
  app:
    image: "alfs-ocr"
    shm_size: '30gb'
    working_dir: /srv
    volumes:
      - .:/srv
      - ./store:/store
      - ./.cache:/root/.cache
    runtime: nvidia
    command: uvicorn alfs_char.web:app --reload --host 0.0.0.0
    environment:
      - STORE_URL
    ports:
      - "${PORT:-8000}:8000"
