version: '2.4'

x-app: &app
  working_dir: /app
  image: "alfs-ocr"
  build: 
    context: .
  volumes:
    - .:/app
    - ./store:/store
    - ./.cache:/root/.cache


services:
  app:
    <<: *app
    shm_size: '30gb'
    runtime: nvidia
    command: uvicorn alfs_char.web:app --reload --host 0.0.0.0
    environment:
      - STORE_URL
      - NVIDIA_VISIBLE_DEVICES
    restart: always
    ports:
      - "${PORT:-8000}:8000"


  tensorboard:
    <<: *app
    command: tensorboard --logdir=runs --host 0.0.0.0 --port=${TENSORBOARD_PORT}
    ports:
      - "${TENSORBOARD_PORT}:${TENSORBOARD_PORT}"

