version: '2.4'

services:
  app:
    image: "alfs-ocr"
    build:
      context: .
    shm_size: '30gb'
    working_dir: /app
    volumes:
      - .:/app
      - ./store:/store
      - ./.cache:/root/.cache
    runtime: nvidia
    command: uvicorn alfs_char.web:app --reload --host 0.0.0.0
    environment:
      - STORE_URL
    restart: on-failure
    ports:
      - "${PORT:-8000}:8000"
