version: '2.4'

services:
  app:
    image: "${DOCKER_REGISTRY}/alfs/char-recog"
    shm_size: '30gb'
    volumes:
      - .:/srv
      - ./store:/store
      - ./.cache:/root/.cache
    runtime: nvidia
    command: uvicorn alfs_char:web:app --reload
    environment:
      - STORE_URL
    ports:
      - "$PORT:5000"
